_base_: '../default.yml'
model_name: 'ovsegmentor_pretrain_vit_bert_cc4m_stage2' # display name in the logger
output: /mnt/petrelfs/xujilan/exps/final_exps/

data:
  train: 
      root_dir: 's3://GCC/GCC12m/'
      meta_file: '/mnt/petrelfs/xujilan/data/cc12m_100/subsets/cc12m_filtered_subset_pair_debug.csv'
      read_from: petrel
      batch_size: 128
  val:
      root_dir: '/mnt/cache/share/images/val/'

  img_aug:
    deit_aug: false
    img_size: 224
    img_scale: [0.4, 1.0]
    interpolation: 'bilinear'
    color_jitter: 0.4
    auto_augment: 'rand-m9-mstd0.5-inc1'
    re_prob: 0.25
    re_mode: 'pixel'
    re_count: 1    

model:
  img_encoder:
    imgnet_pretrained_checkpoint: '/mnt/petrelfs/xujilan/checkpoints/dino_vitbase16_pretrain.pth'

  text_encoder:
    fixed: true

  use_entityloss: true
  use_maskloss: true
  cross_threshold: 0.6
  
train:
  epochs: 10
  base_lr: 1e-5
  min_lr: 1e-6
  warmup_epochs: 0

checkpoint:
  stage1_checkpoint: /mnt/petrelfs/xujilan/exps/cc12m_100/best_miou.pth

