_base_: '../default.yml'
model_name: 'ovsegmentor_pretrain_vit_bert_cc4m_stage1' # display name in the logger
output: /mnt/petrelfs/xujilan/exps/final_exps/

data:
  train: 
      root_dir: 's3://GCC/GCC12m/'
      meta_file: '/mnt/petrelfs/xujilan/data/cc12m_100/subsets/cc12m_filtered_subset_pair_debug.csv'
      read_from: petrel
      batch_size: 256
  val:
      root_dir: '/mnt/cache/share/images/val/'
          
  img_aug:
    deit_aug: true
    img_size: 224
    img_scale: [0.08, 1.0]
    interpolation: 'bilinear'
    color_jitter: 0.4
    auto_augment: 'rand-m9-mstd0.5-inc1'
    re_prob: 0.25
    re_mode: 'pixel'
    re_count: 1

model:
  img_encoder:
    imgnet_pretrained_checkpoint: '/mnt/petrelfs/xujilan/checkpoints/dino_vitbase16_pretrain.pth'

  use_entityloss: true
  
train:
  epochs: 30
  base_lr: 6.4e-4
  warmup_lr: 1.6e-5
  min_lr: 1.6e-4