_base_: 'default.yml'
model_name: 'test_voc12' # display name in the logger
output: /mnt/petrelfs/xujilan/exps/cc12m_100/

model:
  img_encoder:
    imgnet_pretrained_checkpoint: '/mnt/petrelfs/xujilan/checkpoints/dino_vitbase16_pretrain.pth'

evaluate:
  eval_freq: 1
  seg:
    cfg: segmentation/configs/_base_/datasets/pascal_voc12.py